security:
  jwt:
    secret-key: d1f8e9a0b12c34d5e678f9a1b234c56789d012e34567f8a90b12c34d56789e0f
    issuer: petConnect
cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET, POST, PUT, DELETE"
  allowed-headers: "*"
  allow-credentials: true
server:
 port: 8085